# Generated by Django 3.0 on 2022-05-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='notes',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
